[package]
name = "fs2cloud"
authors = ["Christophe Pollet <cpollet@users.noreply.github.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["cargo"] }
clap_complete = "3.1.4"
sha256 = "1.0.3"
uuid = { version = "1.1.1", features = ["v4", "fast-rng"] }
