database: ./database.db3

chunks:
  size: 90MB

pgp:
  # a public key to push, a keypair for pull/fuse
  key: ...
#  # for password-protected keypair
#  passphrase: ...

store:
#   possible values:
#   - log    just display logs about what is happening
#   - s3     uploads chunks to AWS S3
#   - local  moves data to a local folder
  type: log
#  s3:
#    access_key: ...
#    secret_key: ...
#    region: ...
#    bucket: ...
#  local:
#    # the folder will be created if it does not exist
#    path: ...