database: ./database.db3

chunks:
  size: 90MB

pgp:
  public_key: ...

store:
#   possible values:
#   - log    just display logs about what is happening
#   - s3     uploads chunks to AWS S3
  type: log
#  s3:
#    access_key: ...
#    secret_key: ...
#    region: ...
#    bucket: ...